version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./employee_data.db}
    volumes:
      - ./uploads:/app/uploads
      - ./documents.db:/app/documents.db
      - ./employee_data.db:/app/employee_data.db
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: